### ISSUE TITLE
Font size setting effects only the top line

### ISSUE THREAD

**Issue by jlntrt** [lettier/gifcurry#12]
Hey, first thanks for this handy tool. very cool! :+1: 

One bug I found recently: in the current version (2.1.1.0), the size of the font settings effects only the top line, not the bottom line.

**Comment by lettier** [comment]
Hello @jtauert. I am glad you like it. :+1: 

The font size information found on the font choice dialog is not used. I will look into getting this removed as to not cause confusion.

During the text overlay phase, the font size is dynamically calculated to fit in the lower and upper boxes designated for text.

To alter the size of either the top or bottom text, add more or less characters (spaces are allowed).

For example, assume the space character is `s`:

![upper](https://user-images.githubusercontent.com/1661343/30306973-4dd7113c-9749-11e7-82fb-5eb45db91744.gif)

![flower](https://user-images.githubusercontent.com/1661343/30306995-6349d11c-9749-11e7-9442-4d9c95476ad2.gif)

Credit: [Big Buck Bunny](https://peach.blender.org/about//)

**Comment by jtauert** [comment]
Hey @lettier, thanks for your reply.

Okay, get it. I thought I can change the font size for both boxes by setting the size in the font setting dialog.

And by the way: thanks for sharing your tool as open source. :)

**Comment by skerit** [comment]
It would be more useful if the font settings WERE used, though. The font is too small most of the time, even when there's plenty of room to double the size :/
