### ISSUE TITLE
non issue RE:  yaourt

### ISSUE THREAD

**Issue by cirrusUK** [lettier/gifcurry#13]
As a long time Archer i would politely ask that you do not advise folk to install and use yaourt, if one must use an AUR wrapper then cower is the way to go, see [here](http://jasonwryan.com/blog/2013/04/09/helpers/) for my ( and arch communitys) reasoning.
thanks for the code and sorry for the noise
Regards

**Comment by lettier** [comment]
Hello @cirrusUK.

I will change it to the following.

```bash
cd
# Install Git
sudo pacman -S git
# Install Gifcurry from AUR
mkdir -p build_gifcurry
cd build_gifcurry
git clone https://aur.archlinux.org/gifcurry.git
cd gifcurry
makepkg -sic
cd
rm -rf build_gifcurry
gifcurry_gui
gifcurry_cli -?
```

Cheers. :+1:

**Comment by cirrusUK** [comment]
@lettier  Perfect. Thank you sir.
