### ISSUE TITLE
Please rename to gifcurry-2.2.0.0-x86_64.AppImage

### ISSUE THREAD

**Issue by probonopd** [lettier/gifcurry#14]
Please rename `gifcurry-linux-app-image-2.2.0.0` to `gifcurry-2.2.0.0-x86_64.AppImage` to be more compliant with the standard naming scheme. This would also allow me to conduct an automated review for potential inclusion in the AppImageHub central directory of available AppImages.

Thank you.

**Comment by lettier** [comment]
Hello @probonopd.

I have renamed the Gifcurry AppImage. 

I also renamed the AppImage for [Movie Monad](https://github.com/lettier/movie-monad) (an unrelated application).

:+1:

**Comment by probonopd** [comment]
Thank you very much @lettier.
