### ISSUE TITLE
Fails to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [lettier/gifcurry#15]
The AppImage fails to run on Ubuntu 14.04:

```
(gifcurry_gui:4): Gtk-WARNING **: Could not load image 'icon.ico': Couldn't recognize the image file format for file '/run/firejail/appimage/.appimage-7088/usr/share/x86_64-linux-ghc-8.0.2/Gifcurry-2.2.0.0/data/icon.ico'

(gifcurry_gui:4): Gtk-WARNING **: Unknown property: GtkEntry.max-width-chars

(gifcurry_gui:4): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```

This currently prevents gifcurry from being added to the AppImageHub central directory of available AppImages.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/277156332#L706-L710

**Comment by lettier** [comment]
Hello @probonopd.

I ran the AppImage on Ubuntu 14.04. I did find some issues but was not able to reproduce the error you received about there being no schemas.

You can try the updated [AppImage](https://github.com/lettier/gifcurry/releases/download/2.2.0.1/gifcurry-2.2.0.1-x86_64.AppImage).

I was able to get Gifcurry to run successfully on Ubuntu 14.04.

![screenshot_2017-09-19_13-10-52](https://user-images.githubusercontent.com/1661343/30635292-f250984c-9dbf-11e7-932d-7dcfb1f45baa.png)

I will continue to look into the `No GSettings schemas are installed on the system` error. I suspect that the Jenkins image does not have 100% parity with say the desktop image provided by [Canonical](http://releases.ubuntu.com/14.04/ubuntu-14.04.5-desktop-amd64.iso).

:+1:

**Comment by probonopd** [comment]
Did you test it on a "clean" machine where you never had installed Gifcurry before? This may make a difference too.

**Comment by lettier** [comment]
Hello @probonopd.

Yes the Ubuntu 14.04 image was a fresh install with no updates. I simply copied over the AppImage to the virtual machine.

![screenshot_2017-09-21_03-12-58](https://user-images.githubusercontent.com/1661343/30683862-ff74e1dc-9e7c-11e7-8428-fe7e40b14dee.png)

In the latest [AppImage](https://github.com/lettier/gifcurry/releases/download/2.3.0.0/gifcurry-2.3.0.0-x86_64.AppImage), I have bundled the GSettings schemas under `AppDir/usr/share/glib-2.0/schemas/` which is consistent with the `AppRun` export (`export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"`). Please try again.

:+1:

**Comment by probonopd** [comment]
Thanks, added to https://appimage.github.io/gifcurry/. If you like, you can provide a nice screenshot like the one above by adding [AppStream metadata](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps).

**Comment by lettier** [comment]
Hello @probonopd.

I have added the [metadata](https://github.com/lettier/gifcurry/blob/master/packaging/linux/gifcurry.appdata.xml) to the current [AppImage](https://github.com/lettier/gifcurry/releases/download/2.3.0.0/gifcurry-2.3.0.0-x86_64.AppImage).

:+1:
