### ISSUE TITLE
Fails to run on deepin 15.4.1

### ISSUE THREAD

**Issue by jingle0927** [lettier/gifcurry#16]
jingle@jingle:~/Downloads$ ./gifcurry-2.2.0.1-x86_64.AppImage 

** (gifcurry_gui:22406): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(gifcurry_gui:22406): Gtk-WARNING **: Could not load image 'gifcurry-icon.png': Couldn't recognize the image file format for file '/tmp/.mount_gifcurjx8MxN/usr/share/x86_64-linux-ghc-8.0.2/Gifcurry-2.2.0.1/data/gifcurry-icon.png'

(gifcurry_gui:22406): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.

(gifcurry_gui:22406): Gtk-WARNING **: Could not find the icon 'document-open-recent-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
**
Gtk:ERROR:/build/gtk+3.0-NmdvYo/gtk+3.0-3.22.11/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
Aborted
jingle@jingle:~/Downloads$ uname -a
Linux jingle 4.9.0-deepin11-amd64 #1 SMP PREEMPT Deepin 4.9.40-2 (2017-08-12) x86_64 GNU/Linux

**Comment by lettier** [comment]
Hello @jingle0927.

I was able to reproduce your findings. I will have to investigate the `Gtk:ERROR:/build/gtk+3.0-NmdvYo/gtk+3.0-3.22.11/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)` error associated with the AppImage.

However, the [compressed file archive](https://github.com/lettier/gifcurry/releases/download/2.3.0.0/gifcurry-linux-2.3.0.0.tar.gz) does work out-of-the-box with the base Deepin 15.4.1 image.

```bash
wget https://github.com/lettier/gifcurry/releases/download/2.3.0.0/gifcurry-linux-2.3.0.0.tar.gz
tar -xvfz gifcurry-linux-2.3.0.0.tar.gz
./gifcurry-linux-2.3.0.0/bin/gifcurry_gui
```

![screenshot_2017-09-21_04-18-59](https://user-images.githubusercontent.com/1661343/30685913-86053eca-9e84-11e7-97de-321a4eee96e9.png)

**Comment by lettier** [comment]
Hello @jingle0927.

The current [AppImage](https://github.com/lettier/gifcurry/releases/download/2.3.0.0/gifcurry-2.3.0.0-x86_64.AppImage) now works on Deepin 15.4.1.

```bash
# If you would like to install the AppImage, you can run the following
cd
wget "https://raw.githubusercontent.com/lettier/gifcurry/master/packaging/linux/gifcurry-gui-install.sh" -O "gifcurry-gui-install.sh"
chmod +x "gifcurry-gui-install.sh"
./gifcurry-gui-install.sh
```

![screenshot_2017-09-21_22-00-28](https://user-images.githubusercontent.com/1661343/30726508-38dfd516-9f19-11e7-8cec-68c8f9c22497.png)

**Comment by jingle0927** [comment]
OK Thank you
