### ISSUE TITLE
snap-confine

### ISSUE THREAD

**Issue by votafak** [lettier/gifcurry#20]
don't run gifcurry
Ubuntu 16.04.4 - terminal command:
$ gifcurry 
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks

**Comment by lettier** [comment]
Hello @votafak,

I'm not familiar with the [snap-confine](https://github.com/snapcore/snap-confine) tool but the repository says it is no longer used.

Try the following:

```bash
sudo apt-get update
sudo apt-get install snap
snap install gifcurry
sudo snap connect gifcurry:mount-observe
sudo snap connect gifcurry:removable-media
sudo snap connect gifcurry:raw-usb
gifcurry
```

I recently tried it on a fresh copy of Ubuntu 16.04 and it installed.

:+1:
