### ISSUE TITLE
[ERROR] Something went wrong with FFmpeg.

### ISSUE THREAD

**Issue by iuqiddis** [lettier/gifcurry#21]
I'm using gifcurry-3.0.0.1 on an Ubuntu 16.04 system. I used both the pre-built binary, as well the AppImage, but received the same error as follows when trying to save a gif (opened the gui via the command line to see any generated error messages):

[INFO] Writing the temporary frames to: /home/iuqiddis/.cache/gifcurry/gifcurry-frames15716
Error opening filters!
[ERROR] Something went wrong with FFmpeg.

I tried 3 different files. All of them were 1080p x264-encoded h.264 files (mkv container). 

I'm wondering if there is some way to troubleshoot the exact error? Thanks!

**Comment by lettier** [comment]
Hello @iuqiddis,

Try reinstalling FFmpeg. 

```bash
sudo apt-get autoremove --purge ffmpeg
sudo apt-get install ffmpeg
```

What version of FFmpeg are you using?

```bash
ffmpeg -version
```

Try creating a GIF using [Sintel.2010.1080p.mkv](https://download.blender.org/durian/movies/Sintel.2010.1080p.mkv) (© copyright Blender Foundation | [www.sintel.org](https://durian.blender.org/)).

:+1:

**Comment by iuqiddis** [comment]
Hi again.

So i reinstalled ffmepg. The version is as follows:

ffmpeg version 2.8.14-0ubuntu0.16.04.1

I made a clip from the linked mkv file and I get the exact same error. Do you think my ffmpeg version may be outdated?

(side note: if anyone else runs into this error, purging ffmpeg leads to removing a bunch of other packages, so read carefully and re-install applications you do use (in my case, among others, handbrake and kdenline were removed when i purged ffmpeg)

**Comment by lettier** [comment]
Hello @iuqiddis,

Hmm, that file does work.

Try upgrading your version of FFmpeg for Ubuntu 16.04.

http://ubuntuhandbook.org/index.php/2017/10/ffmpeg-3-4-released-install-ubuntu-16-04/

:+1:

**Comment by iuqiddis** [comment]
thanks a lot. it was the outdated version of ffmpeg that seemed to the problem. After installing version 3.4, your linked file, as well as my file worked great. 

Would you consider putting up minimum version requirements (or what you used while building the binary) for the dependencies on the main site for future reference? may be useful for others folks like myself who use LTS distributions and such.

thanks again. and thanks for the super fast response. cheers.

**Comment by iuqiddis** [comment]
thanks for all your help. I'm gonna go ahead and close the issue :)
