### ISSUE TITLE
"FFmpeg is missing decoders. Cannot make GIFs for some videos." (snap)

### ISSUE THREAD

**Issue by Talking-Animal** [lettier/gifcurry#24]
![screenshot from 2018-06-21 00-16-46](https://user-images.githubusercontent.com/27211848/41697812-a1ae424e-74e8-11e8-9160-c6c88572c85d.png)
![screenshot from 2018-06-21 00-17-23](https://user-images.githubusercontent.com/27211848/41697816-a48a3b6c-74e8-11e8-8a76-5d5115bc7191.png)

Ubuntu 18.04
Gifcurry 3.0.0.2 snap
ffmpeg version 3.4.2-2

When clicking 'Open,' a message appears atop the file explorer saying "FFmpeg is missing decoders. Cannot make GIFs for some videos." Trying to open an mp4 file causes nothing to happen.

**Comment by lettier** [comment]
Hello @Talking-Animal,

Thank you for opening an issue.

The Gifcurry snap sandbox environment unfortunately does not ship with certain codecs so this is expected.

Some workarounds:

1) Use the [AppImage](https://github.com/lettier/gifcurry/releases/download/3.0.0.2/gifcurry-3.0.0.2-x86_64.AppImage) which will pick up any codecs that you yourself have installed on your system. Make sure to set the AppImage as [executable](https://ma65p.wordpress.com/2008/08/04/how-to-make-a-file-executable-in-ubuntu/). You can also install the AppImage using this [script](https://github.com/lettier/gifcurry/blob/d9f13e3a22df6bc40f4d21ec722a244a3526734b/packaging/linux/app-image/gifcurry-app-image-install.sh).
2) Download the [binaries for linux](https://github.com/lettier/gifcurry/releases/download/3.0.0.2/gifcurry-linux-3.0.0.2.tar.gz). After you extract the archive, you'll find the executable under `gifcurry-linux-3.0.0.2/bin/gifcurry_gui`. This will use the FFmpeg version you have installed.
3) Run the snap outside of its sandbox environment. It will then find any codecs you yourself have installed on your system. `/snap/gifcurry/current/usr/bin/gifcurry_gui`

If you'd like, I could create a Ubuntu PPA (Personal Package Archive). This would allow you to install Gifcurry via `apt-get` after having added the PPA archive.

:+1:

**Comment by Talking-Animal** [comment]
Thanks for the quick reply!
I have no issues jumping over to the AppImage version, and will download that immediately. I was worried that it was an issue on my end, but am relieved to see that that is not the case. 
If there was a demand for a PPA, I would probably use it, but for now I am more than happy to use the already-available versions until the snap version has increased codec support.

Thanks again.

**Comment by lorods** [comment]
Glad I found those threads. I admit I've thrown a TLDR in the README, but is that issue ever mentioned there? Given how brief can be the "workaround" I think it could be edited, even though it applies only to the Snap store version.
