### ISSUE TITLE
GIF as input

### ISSUE THREAD

**Issue by hellocatfood** [lettier/gifcurry#27]
Can animated gifs be added as an input? It's useful for times when you just need to add text to an existing gif.

ffmpeg can already support animated gifs as input which might remove some of the complexity in supporting it.

**Comment by lettier** [comment]
Hello @hellocatfood,

You can now input/load GIFs instead of just videos.
Try it out in version [5.0.0.0](https://github.com/lettier/gifcurry/releases/tag/5.0.0.0).

:+1:

**Comment by hellocatfood** [comment]
Thanks for including this feature! I've tried it out - from the source download and the appimage - with a couple of gifs (attached) and the program simply exits with a Segmentation Fault error. Most of the gifs I'm using are from https://gifcities.org/

![spinning-internetarchive](https://user-images.githubusercontent.com/151947/44992977-dba56080-af90-11e8-9bfe-cab8ad8891c6.gif)
![tomjerry](https://user-images.githubusercontent.com/151947/44992983-e102ab00-af90-11e8-8aeb-da07b43e5a16.gif)

I'm on Ubuntu 18.04

**Comment by lettier** [comment]
Hello @hellocatfood,

I'm sorry to hear it didn't work but thank you for trying it out.

I tried reproducing the issue on Ubuntu 18.04 but unfortunately could not. I thought it might be a Wayland issue so I tried both X11 and Wayland but in both cases it worked. I used the AppImage 5.0.0.0 download [link](https://github.com/lettier/gifcurry/releases/download/5.0.0.0/gifcurry-5.0.0.0-x86_64.AppImage), made it executable, and ran that.

Was the segmentation fault error the only error output in the terminal? 

![test](https://user-images.githubusercontent.com/1661343/44996813-08994980-af78-11e8-9ba9-909b624bd749.gif)

FFmpeg 3.4.4-0ubuntu0.18.04.1
ImageMagick 6.9.7-4
GStreamer 1.14.0
GTK 3.22.30-1ubu

:+1:

**Comment by hellocatfood** [comment]
Yeah, `Segementation fault (core dumped)` is the only error I get. Here's a screenshot of my terminal window

![screenshot from 2018-09-04 08-46-42](https://user-images.githubusercontent.com/151947/45017282-1fdf4200-b01f-11e8-9313-6ce5935c572d.png)


ImageMagick 6.9.7.4+dfsg-16ubuntu6.3
3.4.4-0ubuntu0.18.04.1
gstreamer 1.14.1-1~ubuntu18.04.1
