### ISSUE TITLE
double snap permissions for "play and record sound"

### ISSUE THREAD

**Issue by stragu** [lettier/gifcurry#29]
I am using the snap (4.0.0.0) provided in Software on Ubuntu 18.04, and I noticed that the "Permissions" menu shows "Play and record sound" twice, the first one off by default, the second one on by default (see screenshot). If I turn the first one on, it is back to off when I reopen the "Permissions" menu. If I turn the second one off, it is back to on when I reopen the "Permissions" menu.

Is this something weird with snaps, or does it need fixing in Gifcurry?

Cheers

![screenshot from 2018-10-22 08-50-40](https://user-images.githubusercontent.com/1747497/47273558-bcfb3780-d5d9-11e8-9f7e-da66361fe25b.png)

**Comment by lettier** [comment]
Hello @stragu,

Thank you for opening up an issue.

I believe this is an issue with Ubuntu Snap.

Try running the following in your terminal:
```bash
sudo snap connect gifcurry:mount-observe
sudo snap connect gifcurry:removable-media
sudo snap connect gifcurry:raw-usb
sudo snap connect gifcurry:pulseaudio
```
and then restart your machine.

In any case, Gifcurry does not record nor playback any sound so you shouldn't need those permissions anyway.

:+1:

**Comment by stragu** [comment]
Hi @lettier 
I ran the commands and restarted, and the "play and record sound" setting is still there twice, but they are both on.
Do you know where I should report that, if it is an Ubuntu Snap issue?

**Comment by lettier** [comment]
Hello @stragu,

I believe https://bugs.launchpad.net/snapcraft is the most appropriate place to file a bug report.

:+1:

**Comment by stragu** [comment]
Thank you, I'm closing this for now :)

**Comment by stragu** [comment]
(in case you're wondering where it ends up: https://bugs.launchpad.net/snapcraft/+bug/1800323 )

**Comment by stragu** [comment]
One more question: why are these permissions even listed if they are not necessary? (sound, system mount information...)

**Comment by lettier** [comment]
Hello @stragu,

I've revised the permissions for the Gifcurry 4.0.0.0 snap.

The permissions are now the following.

```bash
snap interfaces gifcurry
Slot             Plug
:desktop         gifcurry,gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor
:desktop-legacy  gifcurry,gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor
:gsettings       gifcurry,gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor
:home            gifcurry,gnome-characters,gnome-logs
:optical-drive   gifcurry
:wayland         gifcurry,gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor
:x11             gifcurry
-                gifcurry:removable-media
```

You can find the revised version in the snap store. 

![screenshot_2018-10-31_01-45-45](https://user-images.githubusercontent.com/1661343/47768613-31f00080-dcaf-11e8-8227-e250d1b04686.png)

While I tested the revised snap on 16.04 and 18.04, I may have overlooked some scenarios. Please let me know if you come across any issues.

:+1:

**Comment by stragu** [comment]
Hi @lettier 

Thank you so much for the wonderfully long write-up, as I now understand better the ins and outs of it all. It makes a lot more sense. I am very sorry you felt bad about John Lenton's comment (and at first, I read "John Lennon" and thought "John Lennon _definitely_ didn't write anything of the sort in his songs" :laughing: ), it never feels good to read something like that about your personal project you are putting out there for everyone to enjoy (and Glob knows GNU/Linux needs a good GIF maker!).

So again, thank you for the detailed response, and thank you for your hard work. I'll make sure I let people know about your app!

All the best! :+1:

**Comment by stragu** [comment]
And I just read your second message about the new version on the snap store, thank you. I just installed it and I can see only 3 permission lines now. I'll be testing it all soon. Cheers! :)

**Comment by lettier** [comment]
Hello @stragu,

Thank you for testing out the newly revised 4.0.0.0 snap. I greatly appreciate it.

Unfortunately I didn't get a chance to test it on a live host so I wasn't able to confirm USB and external drives. The [removable-media](https://docs.snapcraft.io/the-removable-media-interface/7910) permission should be sufficient though. Users must manually connect it, however.

I couldn't reproduce the segfault regarding certain codecs and the lack of an audio interface so hopefully that issue resolved itself. 

I hope to release the 5.0.0.0 snap soon. With it comes more granular controls and the ability to modify preexisting GIFs. I will wait a little longer just in case these permission changes negatively effect anyone.

:+1:
