### ISSUE TITLE
Not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by computersarecool** [lettier/gifcurry#30]
Hi, your app looks great - unfortunately I can not use it right now.

I am running Ubuntu 18.04, and I have tried to install it from GNOME Software and from Snappy. Both results are the same:
- The GUI looks like this with no way  (to change its size)

![screenshot from 2018-11-14 00-27-10](https://user-images.githubusercontent.com/5414692/48469662-51edec80-e7a4-11e8-8059-cb2ea2b899e9.png)

- On startup there was an error about "FFMPEG missing decoders".

I get the following errors when running from a shell:

````
(gst-plugin-scanner:5693): GStreamer-WARNING **: Failed to load plugin '/snap/gifcurry/6/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstassrender.so': libass.so.5: cannot open shared object file: No such file or directory

(gst-plugin-scanner:5693): GStreamer-WARNING **: Failed to load plugin '/snap/gifcurry/6/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenexr.so': libIlmImf-2_2.so.22: cannot open shared object file: No such file or directory

(gst-plugin-scanner:5693): GStreamer-WARNING **: Failed to load plugin '/snap/gifcurry/6/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstassrender.so': libass.so.5: cannot open shared object file: No such file or directory

(gst-plugin-scanner:5693): GStreamer-WARNING **: Failed to load plugin '/snap/gifcurry/6/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenexr.so': libIlmImf-2_2.so.22: cannot open shared object file: No such file or directory

(gifcurry_gui:5247): GLib-GIO-WARNING **: Error creating IO channel for /proc/mounts: Permission denied (g-file-error-quark, 2)

(gifcurry_gui:5247): Gtk-WARNING **: Theme parsing error: <data>:97:17: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gifcurry_gui:5247): Gtk-WARNING **: Theme parsing error: <data>:98:20: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gifcurry_gui:5247): Gtk-WARNING **: Theme parsing error: <data>:102:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gifcurry_gui:5247): Gtk-WARNING **: Theme parsing error: <data>:103:21: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gifcurry_gui:5247): Gtk-WARNING **: Theme parsing error: <data>:713:25: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version
````

And the following error when I try to open a (valid) .mp4 file:
`/home/user/20180117_004623.mp4: Invalid data found when processing input`

Please let me know how I can help.

**Comment by lettier** [comment]
Hello @computersarecool,

Thank you for opening an issue.

The Gifcurry snap sandbox environment unfortunately does not ship with certain codecs so this is expected. It will work with certain files like MKV, WEBM, and OGV.

Some workarounds:

1) Use the [AppImage](https://github.com/lettier/gifcurry/releases/download/4.0.0.0/gifcurry-4.0.0.0-x86_64.AppImage) which will pick up any codecs that you yourself have installed on your system. Make sure to set the AppImage as [executable](https://ma65p.wordpress.com/2008/08/04/how-to-make-a-file-executable-in-ubuntu/). You can also install the AppImage using this [script](https://github.com/lettier/gifcurry/blob/d2563dabbc0454ffd269697828f7e620633fe4ca/packaging/linux/app-image/gifcurry-app-image-install.sh).
2) Download the [binaries for linux](https://github.com/lettier/gifcurry/releases/download/4.0.0.0/gifcurry-linux-4.0.0.0.tar.gz). After you extract the archive, you'll find the executable under `gifcurry-linux-4.0.0.0/bin/gifcurry_gui`. This will use the FFmpeg version you have installed.
3) Run the snap outside of its sandbox environment. It will then find any codecs you yourself have installed on your system. `/snap/gifcurry/current/usr/bin/gifcurry_gui`

If you'd like, I could create a Ubuntu PPA (Personal Package Archive). This would allow you to install Gifcurry via `apt-get` after having added the PPA.

:+1:

**Comment by computersarecool** [comment]
Yeah the appImage fixed my issue - I thought there was an issue with the GUI!
