### ISSUE TITLE
no decode delegate error

### ISSUE THREAD

**Issue by robertgarrigos** [lettier/gifcurry#31]
I'm using gifcurry appimage on an ubuntu 18.04. I'm trying to convert an mp4 file, which I can preview and save as video (webm format) but not as gif. syslog error shows this:

```
org.gnome.Nautilus[3527]: convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/556.
org.gnome.Nautilus[3527]: convert: no images defined `/home/robert/Documents/Desenvolupament/Presentacions/reveal.js/assets/devel/bcex.gif' @ error/convert.c/ConvertImageCommand/3300.
```

Any idea of what's going on?

Thanks

**Comment by lettier** [comment]
Hello @robertgarrigos,

Thank you for opening an issue.

Please open a terminal and type the following.

```bash
convert --version
```

You should see something like this (taken from `Linux ubuntu18-04 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`).

```bash
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

Is `png` listed under `Delegates (built-in):`?

:+1:

**Comment by lettier** [comment]
Hello @robertgarrigos,

Gifcurry shells out to both the FFmpeg and ImageMagick binaries to produce the final GIF.
You'll need the PNG delegate.

The [ImageMagick package for Ubuntu 18.04 "Bionic"](https://packages.ubuntu.com/bionic/imagemagick) should have all of the delegates you'll need. It is ImageMagick 6 though instead of 7.

Was this a custom build of ImageMagick 7?

:+1:

**Comment by robertgarrigos** [comment]
Yes, I did a build of ImageMagick and, as I said, I finally did the conversion with ffmpeg on terminal.
