### ISSUE TITLE
Keyboard control for changing frames

### ISSUE THREAD

**Issue by hellocatfood** [lettier/gifcurry#36]
Can keyboard control be added to gifcurry to allow for more precise editing? Specifically, I want to be able to go forward and backwards in frames using the keyboard.

Most of the video editors that I've used use Left/Right, K/L or "."/"/" to do this:

https://www.openshot.org/static/files/user-guide/main_window.html
https://docs.blender.org/manual/en/latest/editors/vse/sequencer/editing.html
https://userbase.kde.org/Kdenlive/Manual/Useful_Information/Shortcuts

Can gifcurry implement this and other keyboard shortcuts?

**Comment by lettier** [comment]
Hello @hellocatfood ,

I will try to add this for the next release.

:+1:

**Comment by lettier** [comment]
Hello @hellocatfood 

You can now use <kbd>&lt;</kbd> to seek left and <kbd>&gt;</kbd> to seek right in [version 6.0.0.0](https://github.com/lettier/gifcurry/releases/tag/6.0.0.0).

:+1:
