### ISSUE TITLE
Won't save the GIF

### ISSUE THREAD

**Issue by IvoAndonov** [lettier/gifcurry#38]
I chose many different folders - some on the file system, others on NTFS drives and still won't save it. Only shows a message saying saving failed.
![Снимка от 2019-04-30 17-23-16](https://user-images.githubusercontent.com/41172201/56968998-e8ed0c00-6b6c-11e9-8dee-8add8a67ccbc.png)

**Comment by lettier** [comment]
Hello @IvoAndonov ,

![Screenshot_2019-05-04_03-38-58](https://user-images.githubusercontent.com/1661343/57173369-b48f7f00-6dfc-11e9-9f6e-69027fb7acc0.png)

The screenshot shows the error icon. When you open the file chooser dialog, what does it say near the top?

:+1:

**Comment by IvoAndonov** [comment]
![Снимка от 2019-05-04 16-36-01](https://user-images.githubusercontent.com/41172201/57179837-d9cace80-6e8a-11e9-9e3d-e4b9598f6a9a.png)

I don't understand why you don't make this app compatible with Ubuntu 16.04/Mint 18. Both will be supported until 2021 which means that many people are going to use them until then. Or, if you can give me a link to the older version of the app (which I suspect is compatible with Ubuntu 16), that would be better.
I tried to update ffmpeg but it brings errors and I for one have no intention to switch to ubuntu 18 (Mint 19) with its many glitches when Mint 18.3 works perfect.

**Comment by lettier** [comment]
Hello @IvoAndonov ,

What errors did you receive when attempting to update FFmpeg? I may be able to help you work around them.

Upgrading FFmpeg is the only necessity. Gifcurry itself runs fine on Ubuntu 16.04 and Linux Mint 18. 

You have a few options.

- [Upgrade](https://tecadmin.net/install-ffmpeg-on-linux/) FFmpeg.
- Install FFmpeg via [Snapcraft](https://snapcraft.io/ffmpeg).
- Install Gifcurry via [Snapcraft](https://snapcraft.io/gifcurry). Ubuntu 16.04 is the second most popular distribution. Linux Mint 18 is the sixth most popular distribution. Note that the Snapcraft installation only supports certain media formats.

Beyond that, I can try and support FFmpeg 2.8.15 for the next release.

:+1:

**Comment by IvoAndonov** [comment]
I ran sudo apt-get install ffmpeg and it showed a very long error. I ran this command just now with the intention to copy the error message and no more error but it says ffmpeg is already the newest version - 2.8.15 or something.

Before I downloaded the appimage I tried installing gifcurry via snap but the app itself didn't appear anywhere as installed, even running it from terminal displayed a message no such command was found. So I downloaded the appimage and it worked, except for the part where it won't save the gif.

If you can add support for 2.8.15 that would be great bc atm I have to use a website to turn a video into a gif. It's not bad but if you wanna add text, you gotta scroll down like crazy. The last gif I made (the one on the screenshot above) had about 250 frames and that site displayed every single frame, making the scrolling task almost infinite...

**Comment by lettier** [comment]
Hello @IvoAndonov 

You can now use FFmpeg 2.8.15 with [version 6.0.0.0](https://github.com/lettier/gifcurry/releases/tag/6.0.0.0).

:+1:
