### ISSUE TITLE
Not working with longer durations

### ISSUE THREAD

**Issue by chopin2712** [lettier/gifcurry#40]
I tried to convert a Video into a gif with the full duration of 59 seconds. It didn't work. So I tried to make the same thing with a shorter duration of fewer than 10 seconds and it works. But I need a "fake video" for a markdown file, so I need the full duration of the video. What should I do?

Thank in advance.

**Comment by lettier** [comment]
Hello @chopin2712 

What was the error given?

I tried creating a GIF of a 59 second long video and it worked fine.

Gifcurry doesn't impose any time limits but 59 seconds may be too much for your system given the nature of the video, how much RAM you have, and how much hard drive space is available.

![Screenshot_2019-06-15_18-55-20](https://user-images.githubusercontent.com/1661343/59555251-a2693a80-8f7d-11e9-9e61-ca8ab0e82d7f.png)

Things you can try:

- Lower the frame rate.
- Reduce the size.
- Use a small amount of colors.

:+1:
