### ISSUE TITLE
SRT Subtitle Files Not Working

### ISSUE THREAD

**Issue by joshsweaney** [lettier/gifcurry#41]
SRT Subtitle files do not work on the CLI (no error reported). Tried with multiple SRT files that work fine when used in VLC.

When "Uploading" an SRT file in the GUI the following GTK error appears in the console:

`(<unknown>:47434): Gtk-CRITICAL **: 12:41:12.927: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed`

**Comment by lettier** [comment]
Hello @joshsweaney 

Thank you for opening an issue.

Do you have a sample SRT file?

Gifcurry supports [this format](http://www.visualsubsync.org/help/srt) excluding the formatting tags. 

SRT files from [here](https://durian.blender.org/wp-content/content/download.html) and [here](https://mango.blender.org/download/) were tested and worked fine.

:+1:

**Comment by joshsweaney** [comment]
Ah, figured it out! Format was wrong (Windows line endings), and was using UTF-8 with BOM instead of just UTF-8.

Maybe include an error message that the .srt file couldn't be parsed or something? Thanks for replying.
