### ISSUE TITLE
Save Gif don't work

### ISSUE THREAD

**Issue by heiger1949** [lettier/gifcurry#44]
Please help !
Gifcurry looks great, but saving the gif always brings:
"Didn't work. Check your settings."
I use Ubuntu Linux 16.04.
Thanks

**Comment by lettier** [comment]
Hello,

What is the output when you run Gifcurry from the terminal?

:+1:

**Comment by heiger1949** [comment]
???
I do not know how to use the termninal. I only use graphical programs.

**Comment by lettier** [comment]
Hello,

![open-terminal](https://user-images.githubusercontent.com/1661343/65811734-0d382d80-e18b-11e9-913a-4440968158d4.gif)

To run Gifcurry from the terminal:

1) Right-click on the desktop and select "Open Terminal". You can also press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>t</kbd> and a terminal window will open.
2) From the command prompt, type:

```
gifcurry
```
If that doesn't work, type:

```
gifcurry_gui
```
3) Use Gifcurry as you would normally and make note of the messages being printed in the terminal window.

:+1:

**Comment by heiger1949** [comment]
Thank You, but
typing gifcurry or gifcurry_gui brings "Befehl nicht gefunden."(command not found)
I've tried to change to the directory where gifcurry is installed - 
_cd_  brings "Befehl nicht gefunden." and   _man cd_ brings "Kein Eintrag zu cd im Handbuch".
Should I delete gifcurry and install it new ?

**Comment by heiger1949** [comment]
@lettier 
After I installed gifcurry new it works brillant !
Thank's for this useful tool !

**Comment by wilx** [comment]
Did you use the AppImage executable? In any case, this sounds possibly like the issue I had.. The ImageMagick that comes with Ubuntu has rather restrictive policies set. I had to increase some of the sizes.

```diff
diff -r 1f3699fff237 ImageMagick-6/policy.xml
--- a/ImageMagick-6/policy.xml  Sun Nov 17 07:38:57 2019 +0100
+++ b/ImageMagick-6/policy.xml  Wed Nov 20 00:13:35 2019 +0100
@@ -57,14 +57,16 @@
   <!-- <policy domain="system" name="memory-map" value="anonymous"/> -->
   <!-- <policy domain="system" name="max-memory-request" value="256MiB"/> -->
   <!-- <policy domain="resource" name="temporary-path" value="/tmp"/> -->
-  <policy domain="resource" name="memory" value="256MiB"/>
-  <policy domain="resource" name="map" value="512MiB"/>
+  <!-- policy domain="resource" name="memory" value="256MiB"/ -->
+  <policy domain="resource" name="memory" value="1GiB"/>
+  <policy domain="resource" name="map" value="1GiB"/>
   <policy domain="resource" name="width" value="16KP"/>
   <policy domain="resource" name="height" value="16KP"/>
   <!-- <policy domain="resource" name="list-length" value="128"/> -->
-  <policy domain="resource" name="area" value="128MB"/>
-  <policy domain="resource" name="disk" value="1GiB"/>
+  <policy domain="resource" name="area" value="512MB"/>
+  <policy domain="resource" name="disk" value="2GiB"/>
   <!-- <policy domain="resource" name="file" value="768"/> -->
+  <policy domain="resource" name="file" value="10000"/>
   <!-- <policy domain="resource" name="thread" value="4"/> -->
   <!-- <policy domain="resource" name="throttle" value="0"/> -->
   <!-- <policy domain="resource" name="time" value="3600"/> -->
```

**Comment by heiger1949** [comment]
@wilx 
I use AppImage.

**Comment by lorods** [comment]
Imagemagick seems a trash implementation by now, because even after changing my policy values it throws some a bunch of exceptions. Also, why not link the ffmpeg utility to do the whole thing with the codecs within the program? I'm going to stick to the CLI because that was what was working... 
Tried the old procedure with ffmpeg and no issues. Wonder what's about IM
