### ISSUE TITLE
GUI is not resizable

### ISSUE THREAD

**Issue by AbuMaia** [lettier/gifcurry#45]
Could you make the gui window resizable please? The section that has the start and end times for the gif are below the bottom edge of my screen, where I cannot get to them.
![Screenshot from 2019-09-27 19-07-23](https://user-images.githubusercontent.com/9308040/65809397-6176e980-e15a-11e9-972d-c7d12349d7e7.png)

**Comment by lettier** [comment]
Hello,

I will try to include this in the next release.

:+1:

**Comment by lettier** [comment]
Fixed in [6.0.1.0](https://github.com/lettier/gifcurry/releases/tag/6.0.1.0).

:+1:
