### ISSUE TITLE
Let user select font

### ISSUE THREAD

**Issue by Jereviendrai** [lettier/gifcurry#5]
Hello,

I think a nice feature for this tool would be to let the user select the desired font for captions. Since you use ImageMagick to add the captions, this could just be specified as a parameter to IM.

Cheers!

**Comment by lettier** [comment]
Hello,

That is a great idea. I will look into adding this.

Thanks!

**Comment by lettier** [comment]
![gui](https://cloud.githubusercontent.com/assets/1661343/20337428/155f40f4-ab9f-11e6-878e-d37a437efba2.gif)

You can now pick your own font. Merging into master soon. :+1:

**Comment by Jereviendrai** [comment]
Awesome! I'll be sure to test it!

Thanks a bunch :)
