### ISSUE TITLE
Ubuntu app image issue

### ISSUE THREAD

**Issue by antoinebou13** [lettier/gifcurry#52]
System Info
```
Linux Antoine-Gaming 5.5.8-050508-generic #202003051633 SMP Thu Mar 5 16:37:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux


Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal
```
```
$ ./gifcurry-6.0.0.0-x86_64.AppImage

(gifcurry_gui:7257): GLib-GIO-ERROR **: 10:48:52.526: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)
```

**Comment by lettier** [comment]
Hello,

Which version of GTK are you using?

:+1:

**Comment by antoinebou13** [comment]
2.24.32-4ubuntu4 gtk+2.0
3.24.18-1ubuntu1 gtk+3.0

**Comment by lettier** [comment]
Hello,

I will have to update the AppImage for 20.04.

In the meantime, you can use the [binaries](https://github.com/lettier/gifcurry/releases/download/6.0.0.0/gifcurry-linux-6.0.0.0.tar.gz) located on the [releases](https://github.com/lettier/gifcurry/releases/tag/6.0.0.0) page.
The Gifcurry GUI is located at `./gifcurry-linux-6.0.0.0/bin/gifcurry_gui`.

:+1:

**Comment by antoinebou13** [comment]
ok thank I will test it out

**Comment by volnes** [comment]
Well this error still here

**Comment by johhnry** [comment]
Hi,

I am using Pop!_OS 20.04 and this issue still exists with the latest build : `gifcurry-6.0.0.0-x86_64.AppImage` : 

```
(gifcurry_gui:15019): GLib-GIO-ERROR **: 16:40:09.476: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
```

I have `libgtk-3-0` installed correctly and it used to work before I made the update from 18.04 to ubuntu 20.04

Is there a fix?

**Comment by lettier** [comment]
Hello @johhnry,

I will have to update the AppImage for 20.04.

In the meantime, you can use the [binaries](https://github.com/lettier/gifcurry/releases/download/6.0.0.0/gifcurry-linux-6.0.0.0.tar.gz) located on the [releases](https://github.com/lettier/gifcurry/releases/tag/6.0.0.0) page.
The Gifcurry GUI is located at `./gifcurry-linux-6.0.0.0/bin/gifcurry_gui`.

:+1:

**Comment by CRThaze** [comment]
Can confirm this issue is still occurring (Pop!_OS 20.04) with the latest AppImage. I'm using the binary in the meantime successfully.

**Comment by lettier** [comment]
Hello,

The AppImage has been updated.

:+1:
