### ISSUE TITLE
No video preview on arch 

### ISSUE THREAD

**Issue by LeducH** [lettier/gifcurry#53]
I want to use GIFcurry 

I installed using the AUR when I open the program I get:

Error message 

```
gtksink not found. No video preview available. Install all GStreamer 1.0 plugins
```

I am on arch and have the dependencies installed 

```
❯ pacman -Q | grep -i gst                              
gst-libav 1.16.2-1
gst-plugins-bad 1.16.2-7
gst-plugins-bad-libs 1.16.2-7
gst-plugins-base 1.16.2-1
gst-plugins-base-libs 1.16.2-1
gst-plugins-good 1.16.2-3
gst-plugins-ugly 1.16.2-3
gst-python 1.16.2-2
gst-python2 1.16.2-1
gstreamer 1.16.2-1
phonon-qt5-gstreamer 4.10.0-1
```

How can this be resolved?

**Comment by lettier** [comment]
Hello,

What is the output of `gst-inspect-1.0 | grep libav: | wc -l`.

:+1:

**Comment by LeducH** [comment]
the output is 

 ```
$  gst-inspect-1.0 | grep libav: | wc -l
607
```

**Comment by Qheb** [comment]
Hello,
I had the same issue and I resolved it by installing the following dependency: `gst-plugin-gtk`

**Comment by ratijas** [comment]
Installing `gst-plugin-gtk` indeed solved the issue. And it is only about 50 KiB in size. I wonder, would it make sense to include it in the AppImage?

**Comment by ratijas** [comment]
README links to these pages:

> * [GStreamer >= 1.0](https://gstreamer.freedesktop.org/download/)
>    * [GStreamer Plugins](https://gstreamer.freedesktop.org/modules/)

But they don't even contain a "gtk" substring. I myself didn't know about existence of `gst-plugin-gtk` until today. So, probably it should be included with the distribution.
