### ISSUE TITLE
[ERROR] gst-inspect-1.0: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist

### ISSUE THREAD

**Issue by volnes** [lettier/gifcurry#55]
Ubuntu 20.04.
When i choose file with last binary from: https://github.com/lettier/gifcurry/releases/download/6.0.0.0/gifcurry-linux-6.0.0.0.tar.gz

There an error:
```
[ERROR] gst-inspect-1.0: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist
gifcurry_gui: user error (file not found)
```
![image](https://user-images.githubusercontent.com/5400851/82180472-44f61000-98e9-11ea-97bc-9e683880b8d3.png)

And btw when i choose file 
![image](https://user-images.githubusercontent.com/5400851/82180512-56d7b300-98e9-11ea-9b90-c80adb1d0843.png)

Any recommendations? solutions?

**Comment by lettier** [comment]
Hello,

What is the output of the following?

```bash
gst-inspect-1.0 --version
```

:+1:

**Comment by volnes** [comment]
`gst-inspect-1.0 --version`

gstreamer1.0-tools was not installed sorry(((
but now i got different error:
```
(gifcurry_gui:93620): Gtk-WARNING **: 08:05:38.695: Theme parsing error: <data>:731:25: The style property GtkPaned:handle-size is deprecated and shouldn't be used anymore. It will be removed in a future version
gifcurry_gui: user error (file not found)
```

**Comment by lettier** [comment]
Hello,

Was that the complete output?

:+1:

**Comment by volnes** [comment]
@lettier yes that was complete

**Comment by lettier** [comment]
Hello,

Based on the provided output, the file provided to Gifcurry could no longer be found.

:+1:
