### ISSUE TITLE
Ubuntu20.04 gifcurry

### ISSUE THREAD

**Issue by NorCalDale** [lettier/gifcurry#56]
Aloha!
Not a coder here. 
Sent here from the gifcurry website page.
In a fresh install of ubuntu 20.04, I can get neither the appimage to open (executing file as a program; gifcurry-6.0.0.0-x86_64.AppImage)
nor can i get gifcurry function as an installed app through "ubuntu software" ("FFmpeg is missing decoders. Cannot make GIFs for some videos)

Can anyone help me get gifcurry to work in any way at all?

Cheers!

-Dale

**Comment by lettier** [comment]
Hello,

Download the [gifcurry-linux-6.0.0.0.tar.gz](https://github.com/lettier/gifcurry/releases/download/6.0.0.0/gifcurry-linux-6.0.0.0.tar.gz) archive from the [releases](https://github.com/lettier/gifcurry/releases) page.

After extracting the files, locate `gifcurry_gui` inside the bin folder. Double click that to run the Gifcurry GUI program. 

![Screenshot_2020-05-22_05-53-45](https://user-images.githubusercontent.com/1661343/82635842-318bc300-9bcf-11ea-9265-3cfbff2ca6cb.png)

:+1:

**Comment by NorCalDale** [comment]
Lettier,
Thank you so much! I can not express how grateful i am: thanks again friend!
-Dale

**Comment by gnudimitrios** [comment]
Hi, 

I followed the above steps and despite I have gstreamer1.0-gtk3 installed, I get "gtksink" not found as a return. 

I'm using Ubuntu 20.04, is there anything that I may have missed?

Kind Regards,

Dimitrios

![Screenshot at 2020-06-26 14-39-52](https://user-images.githubusercontent.com/66121246/85854283-c8463380-b7bc-11ea-86cd-64a3a182ae26.png)

**Comment by lettier** [comment]
Hello @gnudimitrios,

Not sure. I have confirmed that having gstreamer1.0-gtk3 installed does provide the gtksink when using Ubuntu 20.04.

![gtksink](https://user-images.githubusercontent.com/1661343/87501123-4fecc880-c62c-11ea-9558-dcdb3de51530.png)


:+1:

**Comment by lettier** [comment]
Hello,

The AppImage found on the [releases](https://github.com/lettier/gifcurry/releases/tag/6.0.0.0) page has been updated to work with Ubuntu 20.04.

:+1:

**Comment by gnudimitrios** [comment]
Thanks @lettier 👍👍👍
