### ISSUE TITLE
Gifcurry looks like vertical hold has gone?

### ISSUE THREAD

**Issue by Marcrp121** [lettier/gifcurry#65]
Hi there,
I'm new here. Forgive me if this has been asked before.
I'm trying to create .gifs on my laptop. A Lenovo T420.
Running Linux Mint 20.1 Ulyssa, 8gb ram, Intel Core i5-2520M bits: 64 type
Graphics Intel 2nd Generation Core Processor Family Integrated Graphics 
           vendor: Lenovo ThinkPad T420 driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0126 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 20.2.6 
           compat-v: 3.0 direct render: 

I am having issues with videos playing on gifcurry.

Does anyone know why gifcurry shows all my source videos like this please?

This is what I see trying to open any video format. It was working fine, than one day all videos look like this before I even start to create a gif?
Any thoughts please?

![Screenshot from 2021-02-04 21-30-50](https://user-images.githubusercontent.com/78567339/106957929-886f0380-6730-11eb-8db7-2f7ac865d6c8.png)

**Comment by lettier** [comment]
Hello,

Unfortunately I cannot reproduce this.

:+1:
