### ISSUE TITLE
Weird message about ffmpeg version

### ISSUE THREAD

**Issue by rado84-github** [lettier/gifcurry#69]
I have ffmpeg 4.4-3 from Arch's "Extra" repo and yet gifcurry keeps telling me the ffmpeg is too old and I need to "upgrade" it to 2.8.15. Using the downgrade package the oldest available version is 4.1-2, so I can't "upgrade" it to 2.8.15.
Any ideas how to fix this?

**Comment by lettier** [comment]
Hello,

It says 

> FFmpeg version too old. Upgrade to __*at least*__ version 2.8.15.

so 4.4-3 qualifies.

Nevertheless, what is the output of `FFmpeg -version`? Is it possible there are two versions of FFmpeg or that Gifcurry is accessing some older version of FFmpeg in some kind of sandboxed environment?

:+1:

**Comment by lettier** [comment]
Hello,

I've confirmed that Gifcurry 6.0.1.0 can generate FFmpeg system commands for FFmpeg 4.4.
No such message is displayed.

![Screenshot_2021-07-11_23-22-30](https://user-images.githubusercontent.com/1661343/125212773-9a277a80-e27d-11eb-8295-c21b6219bab0.png)

:+1:
