### ISSUE TITLE
Gifcurry doesn't support RTL languages

### ISSUE THREAD

**Issue by FeryET** [lettier/gifcurry#70]
Hi.

I'm trying to create a Persian GIF, and while the preview works flawlessly, upon saving the GIF the order of the letters gets reversed, and all letters are rendered in their disconnected form. 

E.g. connected form: فرهود

what will be rendered in GifCurry: د و ه ر ف

I think this issue is ffmpeg related, when you probably call the drawtext function.

**Comment by lettier** [comment]
Hello,

Gifcurry does not interface with FFmpeg. It simply assembles and issues a system command.

![Screenshot_2021-07-11_23-34-15](https://user-images.githubusercontent.com/1661343/125213361-1fac2a00-e280-11eb-876a-b44a3620f919.png)

I wasn't able to reproduce this unfortunately. Try running Gifcurry from the terminal and inspecting the TEXT section.

For example:

```txt
- TEXT:
    - Text: سيب
      - Font:
        - Family:  Sans
        - Size:    34
        - Style:   normal
        - Stretch: normal
        - Weight:  400
```

:+1:
