### ISSUE TITLE
makefile:10: *** missing separator.  Stop

### ISSUE THREAD

**Issue by netmediasurfer** [lettier/gifcurry#8]
UBUNTU 14.04 64 BIT

Unable to install the files provided via sudo git clone ""

When I run sudo make within the gifcurry directory my system outputs ..

makefile:10: *** missing separator.  Stop

**Comment by lettier** [comment]
Hello.

What version of `make` are you using?

```bash
make -v | head -n 1
```

I believe you need at least version 3.82 where they introduced [.RECIPEPREFIX](http://www.codesynthesis.com/~boris/blog/2010/07/28/gnu-make-3-82-released/) which allows one to use a character other than tab to prefix a recipe.

:+1:

**Comment by casouri** [comment]
Man I tried to click that thumb up...
